
----本地城市规模人口产出加成
INSERT  INTO Building_YieldChangesPerPop(BuildingType,YieldType,Yield)
VALUES('BUILDING_CITY_SIZE_TOWN', 'YIELD_CRIME',25),
      ('BUILDING_CITY_SIZE_SMALL', 'YIELD_CRIME',25),
      ('BUILDING_CITY_SIZE_MEDIUM', 'YIELD_CRIME',25),
	  ('BUILDING_CITY_SIZE_LARGE', 'YIELD_CRIME',25),
      ('BUILDING_CITY_SIZE_XL', 'YIELD_CRIME',25),
	  ('BUILDING_CITY_SIZE_XXL', 'YIELD_CRIME',50),
	  ('BUILDING_CITY_SIZE_GLOBAL', 'YIELD_CRIME',50);

----本地城市规模产出加成百分比
INSERT  INTO Building_YieldChanges(BuildingType,YieldType,Yield)VALUES
      ---('BUILDING_CITY_SIZE_TOWN', 'YIELD_CRIME',2),
      ('BUILDING_CITY_SIZE_SMALL', 'YIELD_CRIME',5),
      ('BUILDING_CITY_SIZE_MEDIUM', 'YIELD_CRIME',5),
	  ('BUILDING_CITY_SIZE_LARGE', 'YIELD_CRIME',10),
      ('BUILDING_CITY_SIZE_XL', 'YIELD_CRIME',10),
	  ('BUILDING_CITY_SIZE_XXL', 'YIELD_CRIME',15),
	  ('BUILDING_CITY_SIZE_GLOBAL', 'YIELD_CRIME',15);
		

----本地市政厅等级产出加成百分比
INSERT  INTO Building_YieldModifiers(BuildingType,YieldType,Yield)VALUES
      ('BUILDING_CITY_HALL_LV1', 'YIELD_CRIME',-20),
      ('BUILDING_CITY_HALL_LV2', 'YIELD_CRIME',-8),
      ('BUILDING_CITY_HALL_LV3', 'YIELD_CRIME',5),
	  ('BUILDING_CITY_HALL_LV4', 'YIELD_CRIME',25),
      ('BUILDING_CITY_HALL_LV5', 'YIELD_CRIME',45),
	  ('BUILDING_CITY_PUPPET_GOVERNEMENT', 'YIELD_CRIME',80);


INSERT  INTO Building_YieldChanges(BuildingType,YieldType,Yield)VALUES
      --('BUILDING_CITY_HALL_LV1', 'YIELD_CRIME',-20),
      --('BUILDING_CITY_HALL_LV2', 'YIELD_CRIME',-8),
      ('BUILDING_CITY_HALL_LV3', 'YIELD_CRIME',5),
	  ('BUILDING_CITY_HALL_LV4', 'YIELD_CRIME',5),
      ('BUILDING_CITY_HALL_LV5', 'YIELD_CRIME',10),
	  ('BUILDING_CITY_PUPPET_GOVERNEMENT', 'YIELD_CRIME',10);

