--==========================================================================================================================
-- FONT ICONS
--==========================================================================================================================
-- IconFontTextures
------------------------------------------------------------------------------------------------------------------------	
INSERT INTO IconFontTextures (IconFontTexture, 		IconFontTextureFile)
SELECT	'ICON_FONT_TEXTURE_HEALTH', 				'HealthFontIcons_22';	
------------------------------------------------------------------------------------------------------------------------
-- IconFontMapping
------------------------------------------------------------------------------------------------------------------------	
INSERT INTO IconFontMapping (IconName, 					IconFontTexture,						IconMapping)
SELECT	'ICON_DISEASE',								'ICON_FONT_TEXTURE_HEALTH',					38 UNION ALL
SELECT	'ICON_HEALTH',								'ICON_FONT_TEXTURE_HEALTH',					37 UNION ALL
SELECT	'ICON_PLAGUE',								'ICON_FONT_TEXTURE_HEALTH',					39 UNION ALL
SELECT	'ICON_PLAGUE_AIDS',							'ICON_FONT_TEXTURE_HEALTH',					36 UNION ALL
SELECT	'ICON_PLAGUE_ALCOHOL',						'ICON_FONT_TEXTURE_HEALTH',					34 UNION ALL
SELECT	'ICON_PLAGUE_BONES',						'ICON_FONT_TEXTURE_HEALTH',					41 UNION ALL
SELECT	'ICON_PLAGUE_BRONCHITIS',					'ICON_FONT_TEXTURE_HEALTH',					3 UNION ALL
SELECT	'ICON_PLAGUE_BUBONIC',						'ICON_FONT_TEXTURE_HEALTH',					9 UNION ALL
SELECT	'ICON_PLAGUE_CANCER',						'ICON_FONT_TEXTURE_HEALTH',					7 UNION ALL
SELECT	'ICON_PLAGUE_CHOLERA',						'ICON_FONT_TEXTURE_HEALTH',					25 UNION ALL
SELECT	'ICON_PLAGUE_DANCING',						'ICON_FONT_TEXTURE_HEALTH',					21 UNION ALL
SELECT	'ICON_PLAGUE_DENGUE',						'ICON_FONT_TEXTURE_HEALTH',					45 UNION ALL
SELECT	'ICON_PLAGUE_DYSENTERY',					'ICON_FONT_TEXTURE_HEALTH',					27 UNION ALL
SELECT	'ICON_PLAGUE_FATIGUE',						'ICON_FONT_TEXTURE_HEALTH',					6 UNION ALL
SELECT	'ICON_PLAGUE_FEVER',						'ICON_FONT_TEXTURE_HEALTH',					5 UNION ALL
SELECT	'ICON_PLAGUE_FOOD',							'ICON_FONT_TEXTURE_HEALTH',					19 UNION ALL
SELECT	'ICON_PLAGUE_GOUT',							'ICON_FONT_TEXTURE_HEALTH',					20 UNION ALL
SELECT	'ICON_PLAGUE_HIVES',						'ICON_FONT_TEXTURE_HEALTH',					23 UNION ALL
SELECT	'ICON_PLAGUE_IMPOTENCE',					'ICON_FONT_TEXTURE_HEALTH',					42 UNION ALL
SELECT	'ICON_PLAGUE_INFLUENZA',					'ICON_FONT_TEXTURE_HEALTH',					16 UNION ALL
SELECT	'ICON_PLAGUE_LEG',							'ICON_FONT_TEXTURE_HEALTH',					2 UNION ALL
SELECT	'ICON_PLAGUE_LEPROSY',						'ICON_FONT_TEXTURE_HEALTH',					44 UNION ALL
SELECT	'ICON_PLAGUE_LOCKJAW',						'ICON_FONT_TEXTURE_HEALTH',					4 UNION ALL
SELECT	'ICON_PLAGUE_LUNACY',						'ICON_FONT_TEXTURE_HEALTH',					35 UNION ALL
SELECT	'ICON_PLAGUE_MALAISE',						'ICON_FONT_TEXTURE_HEALTH',					15 UNION ALL
SELECT	'ICON_PLAGUE_MEASLES',						'ICON_FONT_TEXTURE_HEALTH',					17 UNION ALL
SELECT	'ICON_PLAGUE_MENIERE',						'ICON_FONT_TEXTURE_HEALTH',					40 UNION ALL
SELECT	'ICON_PLAGUE_POSSESSION',					'ICON_FONT_TEXTURE_HEALTH',					13 UNION ALL
SELECT	'ICON_PLAGUE_PNEUMONIA',					'ICON_FONT_TEXTURE_HEALTH',					10 UNION ALL
SELECT	'ICON_PLAGUE_RABIES',						'ICON_FONT_TEXTURE_HEALTH',					30 UNION ALL
SELECT	'ICON_PLAGUE_SCURVY',						'ICON_FONT_TEXTURE_HEALTH',					28 UNION ALL
SELECT	'ICON_PLAGUE_SEPTICEMIA',					'ICON_FONT_TEXTURE_HEALTH',					24 UNION ALL
SELECT	'ICON_PLAGUE_SIDS',							'ICON_FONT_TEXTURE_HEALTH',					14 UNION ALL
SELECT	'ICON_PLAGUE_SLEEPING',						'ICON_FONT_TEXTURE_HEALTH',					1 UNION ALL
SELECT	'ICON_PLAGUE_SMALLPOX',						'ICON_FONT_TEXTURE_HEALTH',					12 UNION ALL
SELECT	'ICON_PLAGUE_SYPHILIS',						'ICON_FONT_TEXTURE_HEALTH',					29 UNION ALL
SELECT	'ICON_PLAGUE_SUICIDE',						'ICON_FONT_TEXTURE_HEALTH',					33 UNION ALL
SELECT	'ICON_PLAGUE_TYPHOID',						'ICON_FONT_TEXTURE_HEALTH',					22 UNION ALL
SELECT	'ICON_PLAGUE_TUBERCULOSIS',					'ICON_FONT_TEXTURE_HEALTH',					11 UNION ALL
SELECT	'ICON_PLAGUE_TYPHUS',						'ICON_FONT_TEXTURE_HEALTH',					31 UNION ALL
SELECT	'ICON_PLAGUE_WEILS',						'ICON_FONT_TEXTURE_HEALTH',					26 UNION ALL
SELECT	'ICON_PLAGUE_YELLOW',						'ICON_FONT_TEXTURE_HEALTH',					8 UNION ALL
SELECT	'ICON_PLAGUE_ZIKA',							'ICON_FONT_TEXTURE_HEALTH',					18;
--==========================================================================================================================
--==========================================================================================================================