UPDATE Buildings SET PrereqTech='TECH_JOURNALISM' WHERE Type='BUILDING_MOTHERLAND_CALLS';
UPDATE Buildings SET PrereqTech='TECH_BRONZE_WORKING' WHERE Type='BUILDING_TERRACOTTA_ARMY';
UPDATE Buildings SET PrereqTech='TECH_MEGAENGINEERING' WHERE Type='BUILDING_YANGTZE';
UPDATE Buildings SET PrereqTech='TECH_CITY_SCAPE' WHERE Type='BUILDING_SYDNEY_OPERA_HOUSE';
UPDATE Buildings SET PrereqTech='TECH_MEGAENGINEERING' WHERE Type='BUILDING_ASWAN_DAM';
UPDATE Buildings SET PrereqTech='TECH_CHAOS' WHERE Type='BUILDING_NATIONAL_AUTOCRACY';
UPDATE Buildings SET PrereqTech='TECH_MYSTICISM' WHERE Type='BUILDING_ARTEMIS';
UPDATE Buildings SET PrereqTech='TECH_IRON_WORKING' WHERE Type='BUILDING_STATUE_ZEUS';
UPDATE Buildings SET PrereqTech='TECH_NATURAL_MEDICINE' WHERE Type='BUILDING_HANGING_GARDEN';
UPDATE Buildings SET PrereqTech='TECH_ADVANCED_AGRICULTURE' WHERE Type='BUILDING_PETRA';
UPDATE Buildings SET PrereqTech='TECH_DRAMA' WHERE Type='BUILDING_NATIONAL_CIRCUS';

UPDATE Buildings SET PrereqTech='TECH_EXPLORATION2',Cost=600 WHERE Type='BUILDING_PORCELAIN_TOWER';
UPDATE Buildings SET PrereqTech='TECH_JOURNALISM' WHERE Type='BUILDING_EIFFEL_TOWER';
UPDATE Buildings SET Cost=20000 WHERE Type='BUILDING_LARGE_HADRON_COLLIDER';
UPDATE Buildings SET PrereqTech='TECH_GLOBALIZATION' WHERE Type='BUILDING_BURJ_TOWER';

UPDATE Buildings SET GlobalPlotBuyCostModifier=-35 WHERE Type='BUILDING_PYRAMID';





---倾向


INSERT INTO Building_Flavors(BuildingType,FlavorType,Flavor) VALUES 

	   ('BUILDING_GEOLOGICAL_ANVIL', 'FLAVOR_OFFENSE',250),
       ('BUILDING_GEOLOGICAL_ANVIL', 'FLAVOR_MILITARY_TRAINING',250),
       ('BUILDING_GEOLOGICAL_ANVIL', 'FLAVOR_PRODUCTION',270),

       ('BUILDING_AMERICA_RANCH', 'FLAVOR_MILITARY_TRAINING',10),
	   ('BUILDING_AMERICA_RANCH', 'FLAVOR_MOBILE',			10),
	   ('BUILDING_AMERICA_RANCH', 'FLAVOR_PRODUCTION',		35),
	   ('BUILDING_AMERICA_RANCH', 'FLAVOR_GROWTH',			40),
	   ('BUILDING_AMERICA_RANCH', 'FLAVOR_EXPANSION',		50),

	   ('BUILDING_ROCKEFELLER', 'FLAVOR_GOLD',800),
       ('BUILDING_ROCKEFELLER', 'FLAVOR_HAPPINESS',690),
       ('BUILDING_ROCKEFELLER', 'FLAVOR_CULTURE',580),
	   ('BUILDING_ROCKEFELLER', 'FLAVOR_WONDER',580),
   
	   ('BUILDING_INTELLIGENCE_BUREAU', 'FLAVOR_OFFENSE',220),
       ('BUILDING_INTELLIGENCE_BUREAU', 'FLAVOR_DEFENSE',220),
       ('BUILDING_INTELLIGENCE_BUREAU', 'FLAVOR_ESPIONAGE',220),
	   ('BUILDING_INTELLIGENCE_BUREAU', 'FLAVOR_MILITARY_TRAINING',220),

	     
	   ('BUILDING_FOREIGN_OFFICE', 'FLAVOR_SCIENCE',220),
       ('BUILDING_FOREIGN_OFFICE', 'FLAVOR_GOLD',220),
       ('BUILDING_FOREIGN_OFFICE', 'FLAVOR_DIPLOMACY',220),
	   ('BUILDING_FOREIGN_OFFICE', 'FLAVOR_CULTURE',220),
	   ('BUILDING_FOREIGN_OFFICE', 'FLAVOR_RELIGION',220),

	   ('BUILDING_KGB', 'FLAVOR_SCIENCE',999),
       ('BUILDING_KGB', 'FLAVOR_GOLD',350),
       ('BUILDING_KGB', 'FLAVOR_DIPLOMACY',999),
	   ('BUILDING_KGB', 'FLAVOR_ESPIONAGE',999),

	   ('BUILDING_WASHION_TOWER', 'FLAVOR_DIPLOMACY',600),
	   ('BUILDING_WASHION_TOWER', 'FLAVOR_CULTURE',900),
	   ('BUILDING_WASHION_TOWER', 'FLAVOR_WONDER',870),

	   ('BUILDING_LESHAN_BUDDHA', 'FLAVOR_RELIGION',675),
	   ('BUILDING_LESHAN_BUDDHA', 'FLAVOR_WONDER',555),

	   ('BUILDING_SANKORE', 'FLAVOR_SCIENCE',750),
	   ('BUILDING_SANKORE', 'FLAVOR_WONDER',750),

       ('BUILDING_AP', 'FLAVOR_DIPLOMACY',856),
	   ('BUILDING_AP', 'FLAVOR_CULTURE',350),
	   ('BUILDING_AP', 'FLAVOR_WONDER',550),
	   
	   ('BUILDING_BEILUN_TOWER', 'FLAVOR_NAVAL',670),
       ('BUILDING_BEILUN_TOWER', 'FLAVOR_MILITARY_TRAINING',670),
       ('BUILDING_BEILUN_TOWER', 'FLAVOR_DEFENSE',670),
	   ('BUILDING_BEILUN_TOWER', 'FLAVOR_OFFENSE',670),

	   ('BUILDING_KARRUPP', 'FLAVOR_MOBILE',999),
       ('BUILDING_KARRUPP', 'FLAVOR_MILITARY_TRAINING',999),
       ('BUILDING_KARRUPP', 'FLAVOR_RANGED',999),
	   ('BUILDING_KARRUPP', 'FLAVOR_OFFENSE',999),

	   ('BUILDING_NAVAL_ACADEMY', 'FLAVOR_NAVAL',999),
       ('BUILDING_NAVAL_ACADEMY', 'FLAVOR_MILITARY_TRAINING',999),
	   ('BUILDING_NAVAL_ACADEMY', 'FLAVOR_OFFENSE',999),    
	   ('BUILDING_KARLSTEJN', 'FLAVOR_WONDER',888),
       ('BUILDING_KARLSTEJN', 'FLAVOR_GOLD',888),
       ('BUILDING_KARLSTEJN', 'FLAVOR_CULTURE',888),
	   ('BUILDING_KARLSTEJN', 'FLAVOR_GREAT_PEOPLE',888),

	   ('BUILDING_THE_CAPITOL', 'FLAVOR_SCIENCE',220),
       ('BUILDING_THE_CAPITOL', 'FLAVOR_GOLD',220),
       ('BUILDING_THE_CAPITOL', 'FLAVOR_GROWTH',220),
	   ('BUILDING_THE_CAPITOL', 'FLAVOR_CULTURE',220),
	   ('BUILDING_THE_CAPITOL', 'FLAVOR_GREAT_PEOPLE',220),
	   ('BUILDING_THE_CAPITOL', 'FLAVOR_WONDER',220),

	   ('BUILDING_GUIGU', 'FLAVOR_SCIENCE',999),
       ('BUILDING_GUIGU', 'FLAVOR_GOLD',999),
	   ('BUILDING_GUIGU', 'FLAVOR_CULTURE',999),
	   ('BUILDING_GUIGU', 'FLAVOR_GREAT_PEOPLE',999),
	   ('BUILDING_GUIGU', 'FLAVOR_WONDER',999),

	   ('BUILDING_PEOPLES_HALL', 'FLAVOR_OFFENSE',999),
       ('BUILDING_PEOPLES_HALL', 'FLAVOR_DEFENSE',999),
	   ('BUILDING_PEOPLES_HALL', 'FLAVOR_WONDER',999),
	   ('BUILDING_PEOPLES_HALL', 'FLAVOR_MILITARY_TRAINING',999),

	   ('BUILDING_SOVIET_PALACE', 'FLAVOR_OFFENSE',999),
       ('BUILDING_SOVIET_PALACE', 'FLAVOR_DEFENSE',999),
	   ('BUILDING_SOVIET_PALACE', 'FLAVOR_WONDER',999),
	   ('BUILDING_SOVIET_PALACE', 'FLAVOR_MILITARY_TRAINING',999),

	   ('BUILDING_COOKED_MEDICINE', 'FLAVOR_WONDER',999),
       ('BUILDING_COOKED_MEDICINE', 'FLAVOR_GROWTH',999),

	   ('BUILDING_WHITE_HOUSE', 'FLAVOR_WONDER',999),
       ('BUILDING_WHITE_HOUSE', 'FLAVOR_GROWTH',999),
	   ('BUILDING_WHITE_HOUSE', 'FLAVOR_SCIENCE',999),
       ('BUILDING_WHITE_HOUSE', 'FLAVOR_GREAT_PEOPLE',999),
	   ('BUILDING_WHITE_HOUSE', 'FLAVOR_GOLD',999),
       ('BUILDING_WHITE_HOUSE', 'FLAVOR_CULTURE',999),
	   ('BUILDING_WHITE_HOUSE', 'FLAVOR_TILE_IMPROVEMENT',999),
   
       ('BUILDING_DZIMBABWE', 'FLAVOR_DEFENSE',800),
       ('BUILDING_DZIMBABWE', 'FLAVOR_GOLD',800),
	   ('BUILDING_DZIMBABWE', 'FLAVOR_WONDER',800),

       ('BUILDING_PUMA_PUMKU', 'FLAVOR_RELIGION',999),
	   ('BUILDING_PUMA_PUMKU', 'FLAVOR_WONDER',999),

	    ('BUILDING_MAGINOT_LINE', 'FLAVOR_TILE_IMPROVEMENT',999),
		('BUILDING_MAGINOT_LINE', 'FLAVOR_OFFENSE',700),
       ('BUILDING_MAGINOT_LINE', 'FLAVOR_DEFENSE',999),
	   ('BUILDING_MAGINOT_LINE', 'FLAVOR_WONDER',650),
	   ('BUILDING_MAGINOT_LINE', 'FLAVOR_MILITARY_TRAINING',700),

	   ('BUILDING_MOTHERLAND', 'FLAVOR_OFFENSE',999),
       ('BUILDING_MOTHERLAND', 'FLAVOR_DEFENSE',999),
	   ('BUILDING_MOTHERLAND', 'FLAVOR_MILITARY_TRAINING',999),


	    ('BUILDING_PONTE_VECCHIO', 'FLAVOR_SCIENCE',333),
       ('BUILDING_PONTE_VECCHIO', 'FLAVOR_GOLD',500),
	   ('BUILDING_PONTE_VECCHIO', 'FLAVOR_WONDER',380),

	   ('BUILDING_PONTDUGARD', 'FLAVOR_WONDER',500),
       ('BUILDING_PONTDUGARD', 'FLAVOR_GROWTH',500),

	   ('BUILDING_LIBERATION_GATE', 'FLAVOR_OFFENSE',999),
       ('BUILDING_LIBERATION_GATE', 'FLAVOR_DEFENSE',999),
	   ('BUILDING_LIBERATION_GATE', 'FLAVOR_WONDER',999),
	   ('BUILDING_LIBERATION_GATE', 'FLAVOR_MILITARY_TRAINING',999),

	    ('BUILDING_HELIOS_BUILDING', 'FLAVOR_OFFENSE',800),
       ('BUILDING_HELIOS_BUILDING', 'FLAVOR_DEFENSE',800),
	   ('BUILDING_HELIOS_BUILDING', 'FLAVOR_WONDER',800),
	   ('BUILDING_HELIOS_BUILDING', 'FLAVOR_MILITARY_TRAINING',800),

	    ('BUILDING_KING_SOLOMON', 'FLAVOR_SCIENCE',600),
       ('BUILDING_KING_SOLOMON', 'FLAVOR_GOLD',600),
	   ('BUILDING_KING_SOLOMON', 'FLAVOR_WONDER',600),

	   ('BUILDING_ULUGH_BEG', 'FLAVOR_SCIENCE',340),
	   ('BUILDING_ULUGH_BEG', 'FLAVOR_WONDER',540),

	   ('BUILDING_MONASTERY_OF_METEORA', 'FLAVOR_RELIGION',840),
	   ('BUILDING_MONASTERY_OF_METEORA', 'FLAVOR_WONDER',600),

	    ('BUILDING_REGISTAN', 'FLAVOR_RELIGION',640),
	   ('BUILDING_REGISTAN', 'FLAVOR_WONDER',700),
	    ('BUILDING_REGISTAN', 'FLAVOR_HAPPINESS',340),

		('BUILDING_OSARAGI', 'FLAVOR_MILITARY_TRAINING',750),
		 ('BUILDING_OSARAGI', 'FLAVOR_RELIGION',840),
	   ('BUILDING_OSARAGI', 'FLAVOR_WONDER',480),

	   ('BUILDING_CITADEL_OF_CARCASSONNE', 'FLAVOR_CITY_DEFENSE',350),
	   ('BUILDING_CITADEL_OF_CARCASSONNE', 'FLAVOR_WONDER',390),
	   ('BUILDING_CITADEL_OF_CARCASSONNE', 'FLAVOR_MILITARY_TRAINING',460),

	   ('BUILDING_MONT_SAINT_MICHEL', 'FLAVOR_CITY_DEFENSE',999),
	   ('BUILDING_MONT_SAINT_MICHEL', 'FLAVOR_WONDER',390),
	   ('BUILDING_MONT_SAINT_MICHEL', 'FLAVOR_MILITARY_TRAINING',560),
	   ('BUILDING_MONT_SAINT_MICHEL', 'FLAVOR_DEFENSE',999),

	    ('BUILDING_TORRE', 'FLAVOR_GOLD',543),
	   ('BUILDING_TORRE', 'FLAVOR_WONDER',253),
	   ('BUILDING_TORRE', 'FLAVOR_I_SEA_TRADE_ROUTE',680),

	    ('BUILDING_ISHTARGATE', 'FLAVOR_CITY_DEFENSE',700),
	   ('BUILDING_ISHTARGATE', 'FLAVOR_WONDER',999),
	   ('BUILDING_ISHTARGATE', 'FLAVOR_MILITARY_TRAINING',999),

	    ('BUILDING_GLOBALCNIEMA', 'FLAVOR_CULTURE',660),
	   ('BUILDING_GLOBALCNIEMA', 'FLAVOR_WONDER',580),
	   ('BUILDING_GLOBALCNIEMA', 'FLAVOR_GREAT_PEOPLE',720),

	     ('BUILDING_DIONYSUS', 'FLAVOR_CULTURE',560),
	   ('BUILDING_DIONYSUS', 'FLAVOR_WONDER',530),

	   ('BUILDING_KAMUTHI', 'FLAVOR_SCIENCE',550),
	   ('BUILDING_KAMUTHI', 'FLAVOR_WONDER',550),


	     ('BUILDING_RUSHMORE', 'FLAVOR_HAPPINESS',735),
	    ('BUILDING_RUSHMORE', 'FLAVOR_WONDER',520),
	   ('BUILDING_RUSHMORE', 'FLAVOR_EXPANSION',456),

	   ('BUILDING_ABUSIMBEL', 'FLAVOR_GROWTH',352),
	    ('BUILDING_ABUSIMBEL', 'FLAVOR_WONDER',333),
	   ('BUILDING_ABUSIMBEL', 'FLAVOR_CULTURE',367),

	
	  ('BUILDING_SKARABRAE', 'FLAVOR_CULTURE',352),
	    ('BUILDING_SKARABRAE', 'FLAVOR_WONDER',333),
	   ('BUILDING_SKARABRAE', 'FLAVOR_SCIENCE',367),

	    ('BUILDING_SILKROAD', 'FLAVOR_GOLD',852),
	    ('BUILDING_SILKROAD', 'FLAVOR_WONDER',743),


		('BUILDING_ZHENGGUOQU', 'FLAVOR_GROWTH',852),
	    ('BUILDING_ZHENGGUOQU', 'FLAVOR_WONDER',443),


		 ('BUILDING_MEROE', 'FLAVOR_GOLD',352),
	    ('BUILDING_MEROE', 'FLAVOR_WONDER',333),
	   ('BUILDING_MEROE', 'FLAVOR_PRODUCTION',367),

	   ('BUILDING_MALTA', 'FLAVOR_RELIGION',652),
	    ('BUILDING_MALTA', 'FLAVOR_WONDER',333),
	   ('BUILDING_MALTA', 'FLAVOR_GREAT_PEOPLE',467),


	    ('BUILDING_SPHINX', 'FLAVOR_GOLD',652),
	    ('BUILDING_SPHINX', 'FLAVOR_WONDER',633),
	
	    ('BUILDING_LASCAUX_CAVES', 'FLAVOR_GOLD',352),
	    ('BUILDING_LASCAUX_CAVES', 'FLAVOR_WONDER',633),
		('BUILDING_LASCAUX_CAVES', 'FLAVOR_GROWTH',752),

		 ('BUILDING_YUEYANG', 'FLAVOR_OFFENSE',840),
	    ('BUILDING_YUEYANG', 'FLAVOR_MILITARY_TRAINING',760),


	   ('BUILDING_KNOSSOS', 'FLAVOR_CITY_DEFENSE',952),
	   ('BUILDING_KNOSSOS', 'FLAVOR_WONDER',350),
	   ('BUILDING_KNOSSOS', 'FLAVOR_DEFENSE',920),

	   ('BUILDING_MARKOV', 'FLAVOR_WONDER',999),
	   ('BUILDING_MARKOV', 'FLAVOR_MILITARY_TRAINING',999),

	    ('BUILDING_DIABLO', 'FLAVOR_WONDER',999),
	   ('BUILDING_DIABLO', 'FLAVOR_MILITARY_TRAINING',999),

	   ('BUILDING_ULTIMATOWER', 'FLAVOR_WONDER',783),
	   ('BUILDING_ULTIMATOWER', 'FLAVOR_TILE_IMPROVEMENT',999),
	   ('BUILDING_ULTIMATOWER', 'FLAVOR_GROWTH',999),

	    ('BUILDING_SPACE_FORTRESS', 'FLAVOR_CITY_DEFENSE',999),
	   ('BUILDING_SPACE_FORTRESS', 'FLAVOR_WONDER',999),
	   ('BUILDING_SPACE_FORTRESS', 'FLAVOR_MILITARY_TRAINING',999),
	   ('BUILDING_SPACE_FORTRESS', 'FLAVOR_DEFENSE',999),

	    ('BUILDING_FOLDING_MACHINE', 'FLAVOR_SCIENCE',999),
	   ('BUILDING_FOLDING_MACHINE', 'FLAVOR_WONDER',999),

	   ('BUILDING_FASIL_GHEBBI', 'FLAVOR_CITY_DEFENSE',666),
	   ('BUILDING_FASIL_GHEBBI', 'FLAVOR_WONDER',540),
	   ('BUILDING_FASIL_GHEBBI', 'FLAVOR_MILITARY_TRAINING',666),
	   ('BUILDING_FASIL_GHEBBI', 'FLAVOR_DEFENSE',795),


	   ('BUILDING_VERSAILLES', 'FLAVOR_GOLD',666),
	   ('BUILDING_VERSAILLES', 'FLAVOR_WONDER',666),
	   ('BUILDING_VERSAILLES', 'FLAVOR_SCIENCE',666),
	  

	    ('BUILDING_JURASSIC_PARK', 'FLAVOR_HAPPINESS',999),
	   ('BUILDING_JURASSIC_PARK', 'FLAVOR_WONDER',753),
	   ('BUILDING_JURASSIC_PARK', 'FLAVOR_MILITARY_TRAINING',999),

	    ('BUILDING_SMITHSONIAN', 'FLAVOR_SCIENCE',570),
	   ('BUILDING_SMITHSONIAN', 'FLAVOR_WONDER',540),

	    ('BUILDING_CRYSTAL_PALACE', 'FLAVOR_SCIENCE',670),
	   ('BUILDING_CRYSTAL_PALACE', 'FLAVOR_WONDER',540),
	    ('BUILDING_CRYSTAL_PALACE', 'FLAVOR_GOLD',640),

		('BUILDING_TECHNOMART', 'FLAVOR_PRODUCTION',999),
	   ('BUILDING_TECHNOMART', 'FLAVOR_WONDER',560),
	   ('BUILDING_TECHNOMART', 'FLAVOR_TILE_IMPROVEMENT',300),

	   ('BUILDING_NATIONAL_HOSPITAL', 'FLAVOR_GROWTH',400),
	   ('BUILDING_NATIONAL_HOSPITAL', 'FLAVOR_HAPPINESS',300),

	   	('BUILDING_SATELLITE_NET', 'FLAVOR_ESPIONAGE',700),
	   ('BUILDING_SATELLITE_NET', 'FLAVOR_WONDER',600),

	     ('BUILDING_HELIOS', 'FLAVOR_DEFENSE',800),
	   ('BUILDING_HELIOS', 'FLAVOR_WONDER',900),

	    ('BUILDING_SUMMER_PALACE', 'FLAVOR_GREAT_PEOPLE',400),
	   ('BUILDING_SUMMER_PALACE', 'FLAVOR_WONDER',300),

	   ('BUILDING_LEP', 'FLAVOR_DIPLOMACY',900),
	   ('BUILDING_LEP', 'FLAVOR_EXPANSION',600),
	   ('BUILDING_LEP', 'FLAVOR_SPACESHIP',600),


	   ('BUILDING_MOON_BASE', 'FLAVOR_GOLD',300),
	   ('BUILDING_MOON_BASE', 'FLAVOR_MILITARY_TRAINING',300),

	    ('BUILDING_SKYCITY', 'FLAVOR_GROWTH',900),
	   ('BUILDING_SKYCITY', 'FLAVOR_EXPANSION',900),
	   ('BUILDING_SKYCITY', 'FLAVOR_WONDER',800),
	   ('BUILDING_SKYCITY', 'FLAVOR_TILE_IMPROVEMENT',800),

	   ('BUILDING_SKYNET', 'FLAVOR_MILITARY_TRAINING',900),
	   ('BUILDING_SKYNET', 'FLAVOR_WONDER',800),


	   ('BUILDING_MALBORK', 'FLAVOR_GOLD',400),
	   ('BUILDING_MALBORK', 'FLAVOR_WONDER',300),
	    ('BUILDING_MALBORK', 'FLAVOR_MILITARY_TRAINING',850),

		('BUILDING_KRONBORG', 'FLAVOR_CITY_DEFENSE',670),
	   ('BUILDING_KRONBORG', 'FLAVOR_WONDER',670),
	   ('BUILDING_KRONBORG', 'FLAVOR_MILITARY_TRAINING',670),
	   ('BUILDING_KRONBORG', 'FLAVOR_DEFENSE',670),


	   ('BUILDING_ARCHIMEDES', 'FLAVOR_CITY_DEFENSE',999),
	   ('BUILDING_ARCHIMEDES', 'FLAVOR_WONDER',999),
	   ('BUILDING_ARCHIMEDES', 'FLAVOR_MILITARY_TRAINING',999),

	   ('BUILDING_INTERSTATE_HIGHWAY_SYSTEM', 'FLAVOR_GOLD',160),
	   ('BUILDING_INTERSTATE_HIGHWAY_SYSTEM', 'FLAVOR_INFRASTRUCTURE',160),

	    ('BUILDING_KRAK_DES_CHEVALIERS', 'FLAVOR_CITY_DEFENSE',652),
	   ('BUILDING_KRAK_DES_CHEVALIERS', 'FLAVOR_WONDER',350),
	   ('BUILDING_KRAK_DES_CHEVALIERS', 'FLAVOR_MILITARY_TRAINING',560),
	   ('BUILDING_KRAK_DES_CHEVALIERS', 'FLAVOR_DEFENSE',320),
	   ('BUILDING_KRAK_DES_CHEVALIERS', 'FLAVOR_MOBILE',770),

	   ('BUILDING_CENTERS', 'FLAVOR_GROWTH',486),

	   ('BUILDING_POSEIDON_TEMPLE', 'FLAVOR_NAVAL',999),
	   ('BUILDING_POSEIDON_TEMPLE', 'FLAVOR_NAVAL_RECON',999),
	   ('BUILDING_POSEIDON_TEMPLE', 'FLAVOR_MILITARY_TRAINING',456),
	   ('BUILDING_POSEIDON_TEMPLE', 'FLAVOR_WONDER',850);


---来自城邦
INSERT INTO Building_YieldPerFriend(BuildingType,YieldType,Yield) 
VALUES ('BUILDING_ROCKEFELLER','YIELD_GOLD',100);

INSERT INTO Building_YieldPerAlly(BuildingType,YieldType,Yield) 
VALUES ('BUILDING_ROCKEFELLER','YIELD_GOLD',200);

---若干个地形
--INSERT INTO Building_YieldPerXTerrainTimes100(BuildingType,TerrainType,YieldType,Yield) 
--VALUES('BUILDING_CARPENTER', 'TERRAIN_DESERT', 'YIELD_GOLD',1),
      --('BUILDING_CARPENTER', 'TERRAIN_DESERT', 'YIELD_CULTURE',1);
	
--INSERT INTO Building_YieldPerXFeatureTimes100(BuildingType,FeatureType,YieldType,Yield) 
--VALUES('BUILDING_CARPENTER', 'FEATURE_JUNGLE', 'YIELD_PRODUCTION',2),
      --('BUILDING_CARPENTER', 'FEATURE_FOREST', 'YIELD_PRODUCTION',2);


----间谍偷取产出
INSERT INTO Building_YieldPerEspionageSpy(BuildingType,YieldType,Yield) 
VALUES ('BUILDING_BLETCHLEY_PARK','YIELD_GOLD',25),
       ('BUILDING_BLETCHLEY_PARK','YIELD_PRODUCTION',25),
       ('BUILDING_BLETCHLEY_PARK','YIELD_SCIENCE',25),
	   ('BUILDING_BLETCHLEY_PARK','YIELD_GOLD',15),
	   ('BUILDING_BLETCHLEY_PARK','YIELD_FAITH',15),
       ('BUILDING_BLETCHLEY_PARK','YIELD_CULTURE',15),
       ('BUILDING_BLETCHLEY_PARK','YIELD_SCIENCE',15);



----单位晋升时回血
INSERT INTO Building_UnitTypePrmoteHealGlobal(BuildingType,UnitType,Heal)
SELECT  'BUILDING_BEILUN_TOWER', Type, 50 FROM Units WHERE Domain ='DOMAIN_SEA'; 

INSERT INTO Building_UnitTypePrmoteHealGlobal(BuildingType,UnitType,Heal)
SELECT  'BUILDING_KRAK_DES_CHEVALIERS', Type, 50 FROM Units WHERE CombatClass ='UNITCOMBAT_MOUNTED' AND Domain ='DOMAIN_LAND'; 


---建筑关联改良加成
INSERT INTO Building_ImprovementYieldModifiers(BuildingType,ImprovementType,YieldType,Yield) 
VALUES ('BUILDING_SILKROAD', 'IMPROVEMENT_LATIFUNDIUM', 'YIELD_GOLD',10),
       ('BUILDING_MONASTERY_OF_METEORA', 'IMPROVEMENT_HOLY_SITE', 'YIELD_FAITH',8);



---大津巴布韦
INSERT INTO Building_YieldFromConstruction(BuildingType, YieldType, Yield)
VALUES('BUILDING_DZIMBABWE', 'YIELD_GOLD',100);


-- 建筑来自国际贸易
INSERT INTO Building_YieldFromInternalTR(BuildingType, YieldType, Yield)
VALUES('BUILDING_AMERICA_RANCH', 'YIELD_PRODUCTION',2);


	  
---地形提升
INSERT  INTO Building_TerrainYieldChanges(BuildingType,TerrainType,YieldType,Yield)
SELECT 'BUILDING_SKYCITY', p.Type, h.Type, 3 
FROM Terrains AS p, Yields AS h 
WHERE  p.ID >=0 AND h.ID <8;



INSERT INTO Building_TerrainYieldChanges(BuildingType,TerrainType,YieldType,Yield) VALUES 
('BUILDING_KAMUTHI', 'TERRAIN_DESERT', 'YIELD_SCIENCE',2),
('BUILDING_KRONBORG', 'TERRAIN_OCEAN', 'YIELD_GOLD',2);


---地形百分比提升
INSERT INTO Building_TerrainYieldModifier(BuildingType,TerrainType,YieldType,Yield) VALUES
('BUILDING_HELIOS', 'TERRAIN_DESERT', 'YIELD_SCIENCE',10),
('BUILDING_HELIOS', 'TERRAIN_DESERT', 'YIELD_PRODUCTION',10),	   
('BUILDING_GEOLOGICAL_ANVIL', 'TERRAIN_PLAINS', 'YIELD_PRODUCTION',10);



---地貌提升
INSERT INTO Building_FeatureYieldChanges(BuildingType,FeatureType,YieldType,Yield) 
VALUES ('BUILDING_MONASTERY_OF_METEORA', 'FEATURE_FOREST', 'YIELD_FAITH',1),
       ('BUILDING_GEOTHERMAL_PLANT', 'FEATURE_NEW_VOLCANO', 'YIELD_PRODUCTION',20),
	   ('BUILDING_GEOTHERMAL_PLANT', 'FEATURE_NEW_VOLCANO', 'YIELD_SCIENCE',20),
       ('BUILDING_MEROE', 'FEATURE_OASIS', 'YIELD_PRODUCTION',1),
	   ('BUILDING_MEROE', 'FEATURE_OASIS', 'YIELD_GOLD',2);

---海洋加成
INSERT  INTO Building_SeaPlotYieldChanges(BuildingType,YieldType,Yield)
VALUES('BUILDING_POSEIDON_TEMPLE', 'YIELD_FOOD',2);

--沿河产出加成
INSERT  INTO Building_RiverPlotYieldChanges(BuildingType,YieldType,Yield)
VALUES('BUILDING_MONT_SAINT_MICHEL', 'YIELD_FAITH',2),
      ('BUILDING_MONT_SAINT_MICHEL', 'YIELD_FOOD',1),
      ('BUILDING_ZHENGGUOQU', 'YIELD_FOOD',2);


--湖泊产出加成
INSERT  INTO Building_LakePlotYieldChanges(BuildingType,YieldType,Yield)
VALUES('BUILDING_SUMMER_PALACE', 'YIELD_TOURISM',2),
      ('BUILDING_ZHENGGUOQU', 'YIELD_FOOD',2);


----免费单位	
INSERT  INTO Building_FreeUnits(BuildingType,UnitType,NumUnits)
VALUES ('BUILDING_SPACE_FORTRESS', 'UNIT_AEGIS', 1),
	   ('BUILDING_SPACE_FORTRESS', 'UNIT_DRONE_FIGHTER', 2),
	   ('BUILDING_SPACE_FORTRESS', 'UNIT_BEAM_JUMPER', 1),

	   ('BUILDING_BEILUN_TOWER', 'UNIT_GREAT_ADMIRAL', 1),
       ('BUILDING_PEOPLES_HALL', 'UNIT_GREAT_GENERAL', 2),
	   ('BUILDING_COOKED_MEDICINE', 'UNIT_GREAT_DOCTOR', 1),
	   ('BUILDING_NATIONAL_FINANCE', 'UNIT_MERCHANT', 1),
	   ('BUILDING_PONTE_VECCHIO', 'UNIT_MERCHANT', 1),
	   ('BUILDING_MONASTERY_OF_METEORA', 'UNIT_MISSIONARY', 2),
	   ('BUILDING_KRAK_DES_CHEVALIERS', 'UNIT_GREAT_GENERAL', 1),
	   ('BUILDING_YUEYANG', 'UNIT_SWORDSMAN', 3),

	   ('BUILDING_FOLDING_MACHINE',  'UNIT_SCIENTIST', 2);


--提供资源
INSERT  INTO Building_ResourceQuantity(BuildingType,ResourceType,Quantity)
VALUES ('BUILDING_AMERICA_RANCH', 'RESOURCE_HORSE', 5);


---本地资源提升
INSERT INTO Building_ResourceYieldChanges(BuildingType,ResourceType,YieldType,Yield) 
VALUES ('BUILDING_DZIMBABWE', 'RESOURCE_TEQUILA', 'YIELD_GOLD',5),
       ('BUILDING_DZIMBABWE', 'RESOURCE_SANPEDRO', 'YIELD_GOLD',5),
	   ('BUILDING_DZIMBABWE', 'RESOURCE_INCENSE', 'YIELD_GOLD',5),
	   ('BUILDING_DZIMBABWE', 'RESOURCE_JADE', 'YIELD_GOLD',5),
	   ('BUILDING_DZIMBABWE', 'RESOURCE_LAPIS', 'YIELD_GOLD',5),
       ('BUILDING_DZIMBABWE', 'RESOURCE_AMBER', 'YIELD_GOLD',5),

	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_HORSE',	'YIELD_FOOD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_HORSE',	'YIELD_GOLD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_HORSE',	'YIELD_PRODUCTION',		2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_COW',		'YIELD_FOOD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_COW',		'YIELD_GOLD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_COW',		'YIELD_PRODUCTION',		2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_SHEEP',	'YIELD_FOOD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_SHEEP',	'YIELD_GOLD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_SHEEP',	'YIELD_PRODUCTION',		2),	   
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_BISON',	'YIELD_FOOD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_BISON',	'YIELD_GOLD',			2),
	   ('BUILDING_AMERICA_RANCH',	'RESOURCE_BISON',	'YIELD_PRODUCTION',		2),
	   
	   ('BUILDING_PONTE_VECCHIO', 'RESOURCE_GOLD',  'YIELD_GOLD',5),
       ('BUILDING_PONTE_VECCHIO', 'RESOURCE_SILVER', 'YIELD_GOLD',5),
	   ('BUILDING_PONTE_VECCHIO', 'RESOURCE_GEMS', 'YIELD_GOLD',5),
	   ('BUILDING_PONTE_VECCHIO', 'RESOURCE_AMBER', 'YIELD_GOLD',5),
	   ('BUILDING_PONTE_VECCHIO', 'RESOURCE_LAPIS',   'YIELD_GOLD',5),
       ('BUILDING_PONTE_VECCHIO', 'RESOURCE_JADE', 'YIELD_GOLD',5);

---改良设施数量对资源提升
--INSERT INTO Building_ImprovementResourcesQuantity(BuildingType, ResourceType,ImprovementType,Value) VALUES
--('BUILDING_GUN_POWDER_HOUSE', 'RESOURCE_GUNPOWDER','IMPROVEMENT_QUARRY',1),
--('BUILDING_OIL_WELL', 'RESOURCE_OIL','IMPROVEMENT_WELL',1),
--('BUILDING_ANCIENT_CITY', 'RESOURCE_MANPOWER','IMPROVEMENT_FARM',3),
--('BUILDING_VIRTUAL_IDOL', 'RESOURCE_CONSUMER','IMPROVEMENT_FW_INDUSTRIAL_COMPLEX',1),
--('BUILDING_TITANIUM_FACTORY', 'RESOURCE_TITANIUM','IMPROVEMENT_MINE',1);

---全局资源提升

--INSERT  INTO Building_ResourceYieldChangesGlobal(BuildingType,ResourceType,YieldType,Yield) 
--SELECT 'BUILDING_ANCIENT_CITY', p.Type, h.Type, 1
--FROM Resources AS p, Yields AS h 
--WHERE (p.Type ='RESOURCE_BARLEY' OR p.Type ='RESOURCE_WHEAT') AND (h.Type = 'YIELD_GOLD' OR h.Type = 'YIELD_FOOD' OR h.Type = 'YIELD_PRODUCTION');

INSERT  INTO Building_ResourceYieldChangesGlobal(BuildingType,ResourceType,YieldType,Yield) 
SELECT 'BUILDING_LASCAUX_CAVES', p.Type, h.Type, 1
FROM Resources AS p, Yields AS h 
WHERE (p.Type ='RESOURCE_DEER' OR p.Type ='RESOURCE_BISON'OR p.Type ='RESOURCE_IVORY'OR p.Type ='RESOURCE_HORSE'OR p.Type ='RESOURCE_COW'OR p.Type ='RESOURCE_SHEEP'OR p.Type ='RESOURCE_CRAB' OR p.Type ='RESOURCE_TRUFFLES')AND (h.Type = 'YIELD_GOLD' OR h.Type = 'YIELD_FOOD');

--单位建造速率加成
INSERT  INTO Building_UnitCombatProductionModifiers(BuildingType,UnitCombatType,Modifier)VALUES
('BUILDING_AMERICA_RANCH',	'UNITCOMBAT_MOUNTED',	33),
('BUILDING_AMERICA_RANCH',	'UNITCOMBAT_SETTLER',	33),
('BUILDING_AMERICA_RANCH',	'UNITCOMBAT_WORKER',	33),

('BUILDING_KRAK_DES_CHEVALIERS', 'UNITCOMBAT_MOUNTED',20);

INSERT  INTO Building_DomainProductionModifiers(BuildingType,DomainType,Modifier)
VALUES('BUILDING_KRONBORG', 'DOMAIN_SEA',15);


---建筑与改良设施的资源关联
INSERT INTO Building_ResourceFromImprovement(BuildingType,ResourceType,ImprovementType,Value) VALUES 
('BUILDING_EXPLOSIVE_MATERIAL_FACTORY','RESOURCE_GUNPOWDER', 'IMPROVEMENT_MANUFACTORY', 5),
('BUILDING_THORIUM_REACTOR','RESOURCE_ELECTRICITY', 'IMPROVEMENT_FW_GENERATOR', 5),
('BUILDING_CARPENTER','RESOURCE_LUMBER', 'IMPROVEMENT_BRAZILWOOD_CAMP', 1),
 ('BUILDING_CARPENTER','RESOURCE_LUMBER', 'IMPROVEMENT_LUMBERMILL', 1);

---本地改良提升
INSERT INTO Building_ImprovementYieldChanges(BuildingType,ImprovementType,YieldType,Yield) VALUES 
 ('BUILDING_SANCTUARY', 'IMPROVEMENT_TERRASCAPE', 'YIELD_GOLD',6),
	   ('BUILDING_SANCTUARY', 'IMPROVEMENT_TERRASCAPE', 'YIELD_CULTURE',6),

      ('BUILDING_CARPENTER', 'IMPROVEMENT_BRAZILWOOD_CAMP', 'YIELD_PRODUCTION',1),
	   ('BUILDING_CARPENTER', 'IMPROVEMENT_LUMBERMILL', 'YIELD_PRODUCTION',1),

      ('BUILDING_AMERICA_RANCH', 'IMPROVEMENT_FARM', 'YIELD_GOLD',1),
	  ('BUILDING_AMERICA_RANCH', 'IMPROVEMENT_FARM', 'YIELD_PRODUCTION',1),
	  ('BUILDING_AMERICA_RANCH', 'IMPROVEMENT_PASTURE', 'YIELD_GOLD',1),
	  ('BUILDING_AMERICA_RANCH', 'IMPROVEMENT_PASTURE', 'YIELD_PRODUCTION',1),

      ('BUILDING_WEIGH_HOUSE', 'IMPROVEMENT_CUSTOMS_HOUSE', 'YIELD_GOLD',1),
      ('BUILDING_WEIGH_HOUSE', 'IMPROVEMENT_TRADING_POST', 'YIELD_GOLD',1), 

      ('BUILDING_BIOFACTORY', 'IMPROVEMENT_TERRASCAPE', 'YIELD_FOOD',2),
      ('BUILDING_PLANET_MINE', 'IMPROVEMENT_FW_INDUSTRIAL_COMPLEX', 'YIELD_PRODUCTION',2),
      ('BUILDING_SKARABRAE', 'IMPROVEMENT_CAIRN', 'YIELD_FAITH',1),
      ('BUILDING_KRONBORG', 'IMPROVEMENT_FISHFARM_MOD', 'YIELD_GOLD',1);

---全局改良提升
INSERT INTO Building_ImprovementYieldChangesGlobal(BuildingType,ImprovementType,YieldType,Yield) VALUES 
     -- ('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_FARM', 'YIELD_GOLD',1),
      --('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_FARM', 'YIELD_FOOD',1),
     -- ('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_TERRACE_FARM', 'YIELD_GOLD',1),
	  --('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_TERRACE_FARM', 'YIELD_FOOD',1),
	  --('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_POLDER', 'YIELD_GOLD',1),
	  --('BUILDING_ANCIENT_CITY', 'IMPROVEMENT_POLDER', 'YIELD_FOOD',1),

	  ('BUILDING_DZIMBABWE', 'IMPROVEMENT_SAND_BASE', 'YIELD_PRODUCTION',1),

	  ('BUILDING_BURJALARAB', 'IMPROVEMENT_LANDMARK', 'YIELD_CULTURE',3),
	  ('BUILDING_BURJALARAB', 'IMPROVEMENT_LANDMARK', 'YIELD_TOURISM',3),

	  ('BUILDING_SKARABRAE', 'IMPROVEMENT_QUARRY', 'YIELD_SCIENCE',2),
	  ('BUILDING_SKARABRAE', 'IMPROVEMENT_QUARRY', 'YIELD_PRODUCTION',2),

	  ('BUILDING_SILKROAD', 'IMPROVEMENT_LATIFUNDIUM', 'YIELD_GOLD',2),
	  ('BUILDING_KRONBORG', 'IMPROVEMENT_CUSTOMS_HOUSE', 'YIELD_GOLD',3);

--全局奇观产出加成
INSERT  INTO Building_YieldChangeWorldWonderGlobal(BuildingType,YieldType,Yield)
VALUES('BUILDING_WASHION_TOWER', 'YIELD_CULTURE',8),
      ('BUILDING_CRYSTAL_PALACE', 'YIELD_TOURISM',5);


---全局地形加成
INSERT INTO Building_TerrainYieldChangesGlobal(BuildingType,TerrainType,YieldType,Yield) 
VALUES ('BUILDING_DZIMBABWE', 'TERRAIN_DESERT', 'YIELD_GOLD',1),
       ('BUILDING_MEROE', 'TERRAIN_DESERT', 'YIELD_CULTURE',1),
       ('BUILDING_MEROE', 'TERRAIN_DESERT', 'YIELD_FAITH',1);

---基础产出提升
INSERT INTO Building_YieldChanges (BuildingType,YieldType, Yield)VALUES
('BUILDING_YUEYANG', 'YIELD_GREAT_GENERAL_POINTS',3),
('BUILDING_AMERICA_RANCH', 'YIELD_FOOD',3),
('BUILDING_AMERICA_RANCH', 'YIELD_PRODUCTION',3);


--本城产出百分比加成
INSERT  INTO Building_YieldModifiers(BuildingType,YieldType,Yield)
VALUES('BUILDING_ROCKEFELLER', 'YIELD_GOLD',33),
      ('BUILDING_CENTERS', 'YIELD_SCIENCE',10),
      ('BUILDING_AP', 'YIELD_CULTURE',50),
	  ('BUILDING_FOLDING_MACHINE', 'YIELD_SCIENCE',100),
      ('BUILDING_GLOBALCNIEMA', 'YIELD_CULTURE',33);

----本地人口产出加成
INSERT  INTO Building_YieldChangesPerPop(BuildingType,YieldType,Yield)
VALUES('BUILDING_ROCKEFELLER', 'YIELD_GOLD',20),
      ('BUILDING_WASHION_TOWER', 'YIELD_CULTURE',10),
      ('BUILDING_BURJALARAB', 'YIELD_TOURISM',100),

	  ('BUILDING_PONTE_VECCHIO', 'YIELD_GOLD',100),
      ('BUILDING_MARKOV', 'YIELD_GOLD',-100),
	  ('BUILDING_SPHINX', 'YIELD_GOLD',50),
      ('BUILDING_FOLDING_MACHINE', 'YIELD_GOLD',-50),
	  ('BUILDING_FOLDING_MACHINE', 'YIELD_SCIENCE',100),
      ('BUILDING_NATIONAL_HOSPITAL', 'YIELD_GOLD',-50),
	  ('BUILDING_LEP', 'YIELD_GOLD',-50),
      ('BUILDING_JURASSIC_PARK', 'YIELD_GOLD',-50),
	  ('BUILDING_SKYNET', 'YIELD_GOLD',-50),
      ('BUILDING_ARCHIMEDES', 'YIELD_GOLD',-50),
	  ('BUILDING_DZIMBABWE', 'YIELD_GOLD',25),
      ('BUILDING_AP', 'YIELD_CULTURE',25);

----全局人口产出加成	
INSERT  INTO Building_YieldChangesPerPopInEmpire(BuildingType,YieldType,Yield)
SELECT  'BUILDING_PUMA_PUMKU', Type, 20 FROM Yields WHERE Type ='YIELD_CULTURE'OR Type ='YIELD_FAITH';

INSERT  INTO Building_YieldChangesPerPopInEmpire(BuildingType,YieldType,Yield)
VALUES('BUILDING_ULTIMATOWER', 'YIELD_SCIENCE',50),
      ('BUILDING_TECHNOMART', 'YIELD_PRODUCTION',25);

--硅谷等全局百分比加成
INSERT  INTO Building_GlobalYieldModifiers(BuildingType,YieldType,Yield)
SELECT  'BUILDING_GUIGU', Type, 25 FROM Yields WHERE Type ='YIELD_GOLD' OR Type ='YIELD_SCIENCE'OR Type ='YIELD_CULTURE'OR Type ='YIELD_PRODUCTION';

INSERT  INTO Building_GlobalYieldModifiers(BuildingType,YieldType,Yield)
SELECT  'BUILDING_SKYCITY', Type, 25 FROM Yields WHERE Type ='YIELD_GOLD' OR Type ='YIELD_SCIENCE';

INSERT  INTO Building_GlobalYieldModifiers(BuildingType,YieldType,Yield)
SELECT  'BUILDING_ULUGH_BEG', Type, 10 FROM Yields WHERE Type ='YIELD_SCIENCE';

INSERT  INTO Building_GlobalYieldModifiers(BuildingType,YieldType,Yield)
SELECT  'BUILDING_REGISTAN', Type,10 FROM Yields WHERE Type ='YIELD_GOLD' OR Type ='YIELD_SCIENCE';



----史诗
--INSERT  INTO Building_DomainFreeExperiences(BuildingType,DomainType,Experience)
--VALUES('BUILDING_HEROIC_EPIC', 'DOMAIN_SEA',7),
     -- ('BUILDING_HEROIC_EPIC', 'DOMAIN_LAND',7),
      --('BUILDING_HEROIC_EPIC', 'DOMAIN_AIR',7);

--马尔科夫
INSERT  INTO Building_DomainFreeExperiencesGlobal(BuildingType,DomainType,Experience)
VALUES('BUILDING_MARKOV', 'DOMAIN_SEA',120),
      ('BUILDING_MARKOV', 'DOMAIN_LAND',120),
      ('BUILDING_MARKOV', 'DOMAIN_AIR',120);

----凡尔赛
INSERT  INTO Building_CityWithWorldWonderYieldModifierGlobal(BuildingType,YieldType,Yield)
VALUES('BUILDING_VERSAILLES', 'YIELD_GOLD',33),
      ('BUILDING_VERSAILLES', 'YIELD_SCIENCE',33);

----水晶宫
INSERT  INTO Building_GreatWorkYieldChanges(BuildingType,YieldType,Yield)
VALUES('BUILDING_SMITHSONIAN', 'YIELD_SCIENCE',8),
      ('BUILDING_CRYSTAL_PALACE', 'YIELD_SCIENCE',5),
      ('BUILDING_CRYSTAL_PALACE', 'YIELD_GOLD',5),
	  ('BUILDING_KARLSTEJN', 'YIELD_CULTURE',5),
      ('BUILDING_KARLSTEJN', 'YIELD_GOLD',5);
------------------------------------------------------------------------------------------------------------------------
--转换
------------------------------------------------------------------------------------------------------------------------
--INSERT  INTO Building_YieldFromProcessModifierGlobal(BuildingType,YieldType,Yield)
--SELECT  'BUILDING_ROCKEFELLER', Type, 20 FROM Yields WHERE Type !='YIELD_HEALTH';

INSERT  INTO Building_YieldFromProcessModifierGlobal(BuildingType,YieldType,Yield)
SELECT  'BUILDING_TECHNOMART', Type, 30 FROM Yields WHERE Type !='YIELD_HEALTH';

----骑士堡
INSERT INTO Building_EnableUnitPurchase(BuildingType, UnitClassType,YieldType,CostModifier) 
SELECT 'BUILDING_KRAK_DES_CHEVALIERS', Class, 'YIELD_FAITH',500 FROM Units WHERE Class ='UNITCLASS_KNIGHT'OR Class ='UNITCLASS_LANCER'OR Class ='UNITCLASS_CAVALRY'OR Class ='UNITCLASS_BOMBARD' ; 
------------------------------------------------------------------------------------------------------------------------
-- 城市等级产出加成
------------------------------------------------------------------------------------------------------------------------




INSERT INTO Building_BuildingClassYieldModifiers(BuildingType, BuildingClassType,YieldType,Modifier) 
VALUES  ('BUILDING_KING_SOLOMON', 'BUILDINGCLASS_ACADEMY', 'YIELD_SCIENCE',3),
      ('BUILDING_KING_SOLOMON', 'BUILDINGCLASS_LIBRARY', 'YIELD_GOLD',3),

      ('BUILDING_SANKORE', 'BUILDINGCLASS_ALCHEMIST', 'YIELD_SCIENCE',5),
      ('BUILDING_SANKORE', 'BUILDINGCLASS_UNIVERSITY', 'YIELD_SCIENCE',5),
      ('BUILDING_SANKORE', 'BUILDINGCLASS_PUBLIC_SCHOOL', 'YIELD_SCIENCE',5),
	  ('BUILDING_SANKORE', 'BUILDINGCLASS_LABORATORY', 'YIELD_SCIENCE',5),

	  ('BUILDING_TORRE', 'BUILDINGCLASS_HARBOR', 'YIELD_GOLD',5),
      ('BUILDING_TORRE', 'BUILDINGCLASS_SEAPORT', 'YIELD_GOLD',10),
      ('BUILDING_TORRE', 'BUILDINGCLASS_WEIGH_HOUSE', 'YIELD_GOLD',15),

	  ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_MILITARY_BASE', 'YIELD_PRODUCTION',5),
      ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_MILITARY_BASE', 'YIELD_SCIENCE',5),
	  ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_ARSENAL', 'YIELD_PRODUCTION',5),
      ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_ARSENAL', 'YIELD_SCIENCE',5),
	  ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_MILITARY_ACADEMY', 'YIELD_PRODUCTION',10),
      ('BUILDING_PEOPLES_HALL', 'BUILDINGCLASS_MILITARY_ACADEMY', 'YIELD_SCIENCE',10),

      ('BUILDING_RUSHMORE', 'BUILDINGCLASS_COUNTRY_CLUB', 'YIELD_CULTURE',10),
      ('BUILDING_RUSHMORE', 'BUILDINGCLASS_AMUSEMENT_PARK', 'YIELD_CULTURE',10),
      ('BUILDING_RUSHMORE', 'BUILDINGCLASS_THEME_PARK', 'YIELD_CULTURE',15),

	  ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_CINEMA', 'YIELD_TOURISM',20),
      ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_TV_STATION', 'YIELD_TOURISM',20),
      ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_DIGITAL_NETWORK', 'YIELD_TOURISM',25),
	  ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_VIDEO_GAME_COMPANY', 'YIELD_TOURISM',25),
	  ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_OPERA_HOUSE', 'YIELD_TOURISM',15),
      ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_BROADCAST_TOWER', 'YIELD_TOURISM',15),
      ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_THEME_PARK', 'YIELD_TOURISM',15),
	  ('BUILDING_GLOBALCNIEMA', 'BUILDINGCLASS_BEVERAGE_FACTORY', 'YIELD_TOURISM',15),

	  ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_FACTORY', 'YIELD_PRODUCTION',15),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_PUBLIC_SCHOOL', 'YIELD_SCIENCE',15),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_CITY_HALL_LV1', 'YIELD_CULTURE',5),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_CITY_HALL_LV2', 'YIELD_CULTURE',10),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_CITY_HALL_LV3', 'YIELD_CULTURE',20),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_CITY_HALL_LV4', 'YIELD_CULTURE',33),
      ('BUILDING_SOVIET_PALACE', 'BUILDINGCLASS_CITY_HALL_LV5', 'YIELD_CULTURE',33);


INSERT INTO Building_BuildingClassYieldModifiers(BuildingType, BuildingClassType,YieldType,Modifier) 
SELECT  'BUILDING_INTERSTATE_HIGHWAY_SYSTEM', Type, 'YIELD_GOLD',5 FROM BuildingClasses WHERE Type LIKE 'BUILDINGCLASS_CITY_HALL%'; 
------------------------------------------------------------------------------------------------------------------------
-- 阿布辛贝勒、古城
------------------------------------------------------------------------------------------------------------------------
INSERT INTO Building_YieldFromOtherYield(BuildingType, InYieldType,InYieldValue,OutYieldType,OutYieldValue) VALUES
('BUILDING_LESHAN_BUDDHA', 'YIELD_FAITH',50, 'YIELD_CULTURE',10),
('BUILDING_ABUSIMBEL', 'YIELD_FAITH',50, 'YIELD_SCIENCE',10);

------------------------------------------------------------------------------------------------------------------------
-- 情报局免费晋升关联战斗类型
------------------------------------------------------------------------------------------------------------------------
INSERT  INTO UnitPromotions_UnitCombats(PromotionType,UnitCombatType)
SELECT  'PROMOTION_SPY_ADJACENCY_BUFF', Type  FROM UnitCombatInfos WHERE ID !=-1;


------------------------------------------------------------------------------------------------------------------------
--水晶宫
------------------------------------------------------------------------------------------------------------------------
INSERT  INTO Building_ImprovementYieldChangesGlobal(BuildingType,ImprovementType,YieldType,Yield)
SELECT  'BUILDING_CRYSTAL_PALACE', Type, 'YIELD_TOURISM' ,5 FROM Improvements WHERE CreatedByGreatPerson=1;

CREATE TRIGGER Building_ImprovementYieldChangesGlobal_Extra2
AFTER INSERT ON Improvements
WHEN NEW.CreatedByGreatPerson = 1
BEGIN
  INSERT INTO Building_ImprovementYieldChangesGlobal(BuildingType,ImprovementType,YieldType,Yield)
    VALUES('BUILDING_CRYSTAL_PALACE',NEW.Type,'YIELD_TOURISM',5);
END;


---全局专家产出
INSERT INTO Building_SpecialistYieldChanges(BuildingType,	SpecialistType,	YieldType,	  Yield)
--SELECT     'BUILDING_SANKORE',	              'SPECIALIST_SCIENTIST',	   'YIELD_GOLD',	 -3  UNION ALL
SELECT     'BUILDING_BURJALARAB',	              'SPECIALIST_MUSICIAN',	   'YIELD_TOURISM',	 1  UNION ALL
SELECT     'BUILDING_BURJALARAB',	                  'SPECIALIST_WRITER',	   'YIELD_TOURISM',1 UNION ALL
SELECT     'BUILDING_BURJALARAB',	      'SPECIALIST_ARTIST',	   'YIELD_TOURISM',	 1 UNION ALL
SELECT     'BUILDING_KING_SOLOMON',	      'SPECIALIST_SCIENTIST',	   'YIELD_SCIENCE',	 1  UNION ALL
SELECT     'BUILDING_KING_SOLOMON',	      'SPECIALIST_MERCHANT',	       'YIELD_GOLD',	 1 ;
--SELECT     'BUILDING_MONASTERY_OF_METEORA',	      'SPECIALIST_WRITER',	   'YIELD_FAITH',	 1  UNION ALL
--SELECT     'BUILDING_MONASTERY_OF_METEORA',	      'SPECIALIST_ARTIST',	       'YIELD_FAITH',	 1 ;

----本地专家产出
INSERT INTO Building_SpecialistYieldChangesLocal(BuildingType,	SpecialistType,	YieldType,	  Yield)
--SELECT     'BUILDING_ANCIENT_CITY',	              'SPECIALIST_ENGINEER',	   'YIELD_FOOD',	 1  UNION ALL
SELECT     'BUILDING_ROCKEFELLER',	              'SPECIALIST_MERCHANT',	   'YIELD_GOLD',	 2  UNION ALL
SELECT     'BUILDING_KNOSSOS',	                  'SPECIALIST_ENGINEER',	   'YIELD_PRODUCTION',1 UNION ALL

SELECT     'BUILDING_AP',	                      'SPECIALIST_WRITER',	       'YIELD_CULTURE',	 1  UNION ALL
SELECT     'BUILDING_ORE_REFINERIES',	          'SPECIALIST_ENGINEER',	   'YIELD_PRODUCTION',	 1  ;



--间谍速率
UPDATE Buildings SET EspionageModifier=5 ,FoodKept=-10 WHERE BuildingClass='BUILDINGCLASS_CITY_SIZE_LARGE';
UPDATE Buildings SET EspionageModifier=10,FoodKept=-10 WHERE BuildingClass='BUILDINGCLASS_CITY_SIZE_XL';
UPDATE Buildings SET EspionageModifier=10,FoodKept=-15 WHERE BuildingClass='BUILDINGCLASS_CITY_SIZE_XXL';
UPDATE Buildings SET EspionageModifier=10,FoodKept=-20 WHERE BuildingClass='BUILDINGCLASS_CITY_SIZE_GLOBAL';






--人造生态圈
INSERT  INTO Building_FeatureYieldChanges(BuildingType, 	FeatureType, 	YieldType, 		Yield)
SELECT 'BUILDING_SANCTUARY', p.Type, h.Type,  6 
FROM Features AS p, Yields AS h 
WHERE (p.Type ='FEATURE_ATOLL' OR p.Type ='FEATURE_OASIS') AND (h.Type = 'YIELD_GOLD' OR h.Type = 'YIELD_CULTURE');





--建筑为建造的单位战斗类型提供经验值
INSERT INTO Building_UnitCombatFreeExperiences (BuildingType, UnitCombatType, Experience) VALUES
('BUILDING_FIREARM_WORKSHOP', 'UNITCOMBAT_ARMOR', 15),
('BUILDING_FIREARM_WORKSHOP', 'UNITCOMBAT_MELEE', 15),
('BUILDING_FIREARM_WORKSHOP', 'UNITCOMBAT_SIEGE', 15);


-----硅谷
INSERT  INTO Policy_BuildingClassYieldChanges(PolicyType,BuildingClassType ,YieldType ,YieldChange)
SELECT  Type, 'BUILDINGCLASS_GUIGU','YIELD_TOURISM',  8  FROM Policies WHERE PolicyBranchType='POLICY_BRANCH_FREEDOM';

INSERT  INTO Building_SpecialistYieldChanges
       (BuildingType,SpecialistType ,YieldType ,Yield)
VALUES ('BUILDING_GUIGU','SPECIALIST_SCIENTIST','YIELD_SCIENCE' ,  4 ),	 
	   ('BUILDING_GUIGU','SPECIALIST_MERCHANT','YIELD_GOLD' ,     4 ),
	   ('BUILDING_GUIGU','SPECIALIST_ENGINEER','YIELD_PRODUCTION',4 ),
	   ('BUILDING_GUIGU','SPECIALIST_MUSICIAN','YIELD_CULTURE' ,  4 ),
	   ('BUILDING_GUIGU','SPECIALIST_ARTIST','YIELD_GOLDEN_AGE_POINTS',4),
	   ('BUILDING_GUIGU','SPECIALIST_WRITER','YIELD_CULTURE' ,  4 ),
	   ('BUILDING_GUIGU','SPECIALIST_DOCTOR','YIELD_HEALTH'   , 4);


----啊布辛贝勒
INSERT INTO Building_BuildingClassYieldChanges (BuildingType, 	BuildingClassType, 	YieldType, YieldChange)
SELECT 	'BUILDING_ABUSIMBEL', 	'BUILDINGCLASS_TEMPLE',	'YIELD_CULTURE', 	1;



-----苏维埃宫
INSERT  INTO Policy_BuildingClassHappiness(PolicyType,BuildingClassType ,Happiness)
SELECT Type, 'BUILDINGCLASS_SOVIET_PALACE', 2  FROM Policies WHERE PolicyBranchType='POLICY_BRANCH_ORDER';



INSERT  INTO Policy_BuildingClassYieldChanges(PolicyType,BuildingClassType ,YieldType ,YieldChange)
SELECT p.Type, 'BUILDINGCLASS_SOVIET_PALACE', h.Type,  5 
FROM Policies AS p, Yields AS h 
WHERE (p.PolicyBranchType ='POLICY_BRANCH_ORDER' AND h.Type = 'YIELD_SCIENCE') OR (p.PolicyBranchType ='POLICY_BRANCH_ORDER' AND h.Type = 'YIELD_PRODUCTION');



--雷基斯坦
INSERT INTO Building_BuildingClassYieldChanges
		(BuildingType, 			BuildingClassType, 	YieldType, 		YieldChange)
SELECT 	'BUILDING_REGISTAN', 	BuildingClass,		'YIELD_FAITH', 	4
FROM Buildings WHERE FaithCost > 0 AND Cost < 0 ;

CREATE TRIGGER REGISTAN_BuildingClassYieldChanges
AFTER INSERT ON Buildings
WHEN NEW.FaithCost > 0 AND NEW.Cost < 0
BEGIN
	INSERT INTO Building_BuildingClassYieldChanges
			(BuildingType, 			BuildingClassType, 	YieldType, 			YieldChange)
	VALUES 	('BUILDING_REGISTAN', NEW.BuildingClass,	'YIELD_FAITH', 	4);
END;


INSERT INTO Building_BuildingClassYieldChanges
		(BuildingType, 			BuildingClassType, 	YieldType, 		YieldChange)
SELECT 	'BUILDING_REGISTAN', 	BuildingClass,		'YIELD_CULTURE', 	4
FROM Buildings WHERE FaithCost > 0 AND Cost < 0 ;

CREATE TRIGGER REGISTAN_BuildingClassYieldChanges2
AFTER INSERT ON Buildings
WHEN NEW.FaithCost > 0 AND NEW.Cost < 0
BEGIN
	INSERT INTO Building_BuildingClassYieldChanges
			(BuildingType, 			BuildingClassType, 	YieldType, 			YieldChange)
	VALUES 	('BUILDING_REGISTAN', NEW.BuildingClass,	'YIELD_CULTURE', 	4);
END;









